require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/v1/auths", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # V1::Auth. As you add validations to V1::Auth, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # V1::AuthsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  let!(:user) { create(:user) }
  let(:password) { '540512' }

  describe "GET /index" do
    it "renders a successful response" do
      V1::Auth.create! valid_attributes
      get v1_auths_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      auth = V1::Auth.create! valid_attributes
      get v1_auth_url(auth), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new V1::Auth" do
        expect {
          post v1_auths_url,
               params: { v1_auth: valid_attributes }, headers: valid_headers, as: :json
        }.to change(V1::Auth, :count).by(1)
      end

      it "renders a JSON response with the new v1_auth" do
        post v1_auths_url,
             params: { v1_auth: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new V1::Auth" do
        expect {
          post v1_auths_url,
               params: { v1_auth: invalid_attributes }, as: :json
        }.to change(V1::Auth, :count).by(0)
      end

      it "renders a JSON response with errors for the new v1_auth" do
        post v1_auths_url,
             params: { v1_auth: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested v1_auth" do
        auth = V1::Auth.create! valid_attributes
        patch v1_auth_url(auth),
              params: { v1_auth: new_attributes }, headers: valid_headers, as: :json
        auth.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the v1_auth" do
        auth = V1::Auth.create! valid_attributes
        patch v1_auth_url(auth),
              params: { v1_auth: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the v1_auth" do
        auth = V1::Auth.create! valid_attributes
        patch v1_auth_url(auth),
              params: { v1_auth: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested v1_auth" do
      auth = V1::Auth.create! valid_attributes
      expect {
        delete v1_auth_url(auth), headers: valid_headers, as: :json
      }.to change(V1::Auth, :count).by(-1)
    end
  end

  describe "POST /v1/auths/login" do
    context 'success' do
      it "user login" do
        post login_v1_auths_path, params: {userid: user.userid, password: password}
        expect(response).to have_http_status(:success)
        expect(response_json.keys.sort).to eq %w[access access_expires_at csrf refresh refresh_expires_at]
      end
    end
  end

  describe "POST /v1/auths/logout" do
    context 'success' do
      before do
        payload = { user_id: user.userid }
        session = JWTSessions::Session.new(payload: payload, refresh_by_access_allowed: true)
        tokens = session.login
        headers = {}
        headers[JWTSessions.access_header] = "Bearer #{tokens[:access]}"
        headers[JWTSessions.csrf_header] = tokens[:csrf]
        #delete :destroy
        post logout_v1_auths_path(user.userid), headers: headers
      end

      it do
        expect(response).to be_successful
        expect(response_json).to eq 'ok'
      end
    end

  end


end
